### ISSUE TITLE
지난주부터 금일까지 팀 활동내용 정리 및 팀 Wiki에 정리

### ISSUE THREAD

**Issue by junsix** [18-2-SKKU-OSS/2018-2-OSS-L6#1]
지난주부터 금일까지 팀 활동내용 정리 및 팀 Wiki에 정리

**Comment by rjsgmlsms126** [comment]
1주차 개발환경 구축,프로그램 테스트,이슈사항 토론

**Comment by yuneg11** [comment]
[Wiki](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki/팀-활동내용-정리) 디자인 정리

**Comment by kevhahn97** [comment]
1주차 코딩 컨벤션 정독, 팀 목표 관련 논의
