### ISSUE TITLE
설정변경시 재시작 문제

### ISSUE THREAD

**Issue by JunhyeonMoon** [18-2-SKKU-OSS/2018-2-OSS-L6#11]
프로그램의 설정을 변경한 후 재시작이 필요한 부분이 있음(언어변경 등)  
하지만 지금 재시작을 할려면 프로그램을 직접 껐다가 켜야함  

![image](https://user-images.githubusercontent.com/37601694/49431841-b1fb1000-f7f1-11e8-8b8e-e55ab1124b90.png)

이런식으로 버튼 추가  
![image](https://user-images.githubusercontent.com/37601694/49432066-32217580-f7f2-11e8-9d20-a8fb1f034e14.png)

**Comment by yuneg11** [comment]
프로그램을 재시작 하겠냐는 메시지를 띄워도 괜찮을 것 같아요

**Comment by junsix** [comment]
이 부분 얼마나 진행됬나요?
