### ISSUE TITLE
코딩 스타일과 commit/Pull Request 가이드라인 Wiki에 정리

### ISSUE THREAD

**Issue by kevhahn97** [18-2-SKKU-OSS/2018-2-OSS-L6#12]
## Wiki 링크
* [Coding style](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki/%EC%BD%94%EB%94%A9-%EC%8A%A4%ED%83%80%EC%9D%BC)
* [Commit & PR](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki/Commit-&-Pull-Request)

현재 정리 중입니다. 정리가 끝나고 나면 다음 사항을 확인해 주세요.
## 확인 사항
1. 코딩 스타일 - 특히, naming conventions
2. Commit log 양식
3. Pull Request 요구 사항

**Comment by junsix** [comment]
가능하면 한국어로 올려주세요.

**Comment by kevhahn97** [comment]
Wiki 작성 완료하여 링크 등록했습니다.
