### ISSUE TITLE
체계적 Wiki 정리의 필요성

### ISSUE THREAD

**Issue by kevhahn97** [18-2-SKKU-OSS/2018-2-OSS-L6#14]
### Custom side bar
Wiki 사용성을 향상시키기 위해 필요함
* Page 디렉토리를 정의
* 이를 Custom side bar에 표현
  * Wiki [Home](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki)

**Comment by yuneg11** [comment]
관련 프로젝트를 만들었어요 https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/projects/5

**Comment by kevhahn97** [comment]
Feedback 감사합니다.
다음 사항 확인 바랍니다.
1. Custom side bar 관련 링크 추가
2. 페이지 디자인 관련 추가 의견 제시 바랍니다.
3. 세부 Feedback은 @yuneg11 님께서 만드신 프로젝트에서 진행하겠습니다.

**Comment by junsix** [comment]
이슈 완료 됬나요?

**Comment by yuneg11** [comment]
각자 개인활동 내용만 정리하면 될 것 같아요
