### ISSUE TITLE
[NOTICE] Wiki page 제목 수정 시 custom side bar에도 반영

### ISSUE THREAD

**Issue by kevhahn97** [18-2-SKKU-OSS/2018-2-OSS-L6#15]
Wiki page의 제목이 수정될 경우, Custom side bar에 작성된 링크 또한 수정되어야 하므로 이 부분 숙지해 주십시오.

**Comment by kevhahn97** [comment]
위키가 완전히 완성될 때까지 close하지 말아 주세요.

**Comment by yuneg11** [comment]
페이지 추가는 더 없을 것 같아서 이슈 닫을게요
