### ISSUE TITLE
개인 GitHub ID를 Wiki에 정리

### ISSUE THREAD

**Issue by yuneg11** [18-2-SKKU-OSS/2018-2-OSS-L6#2]
[팀명 : 2018-2-OSS-L6](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki/팀명-:-2018-2-OSS-L6)

링크로 추가해 주세요

**Comment by junsix** [comment]
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki 에 다시 정리했습니다

**Comment by yuneg11** [comment]
[Home](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki)의 디자인을 변경했습니다.
