### ISSUE TITLE
issue 재현 @junsix

### ISSUE THREAD

**Issue by junsix** [18-2-SKKU-OSS/2018-2-OSS-L6#20]
테스트 이름:	SingleSecret_MinionToHero_PlayerAttackTest
테스트 전체 이름:	HDTTests.Hearthstone.Secrets.SecretEventHandlerTest.SingleSecret_MinionToHero_PlayerAttackTest
테스트 소스:	C:\Users\home\Desktop\hs\Hearthstone-Deck-Tracker\HDTTests\Hearthstone\Secrets\SecretEventHandlerTest.cs : 줄 170
테스트 결과:	실패
테스트 지속 시간:	0:00:00.0020667

Result StackTrace:	
위치: HDTTests.Hearthstone.Secrets.SecretEventHandlerTest.VerifySecrets(Int32 index, List`1 allSecrets, String[] triggered) 파일 C:\Users\home\Desktop\hs\Hearthstone-Deck-Tracker\HDTTests\Hearthstone\Secrets\SecretEventHandlerTest.cs:줄 420
   위치: HDTTests.Hearthstone.Secrets.SecretEventHandlerTest.SingleSecret_MinionToHero_PlayerAttackTest() 파일 C:\Users\home\Desktop\hs\Hearthstone-Deck-Tracker\HDTTests\Hearthstone\Secrets\SecretEventHandlerTest.cs:줄 174
Result 메시지:	Assert.AreEqual이(가) 실패했습니다. 예상 값: <True>. 실제 값: <False>. Freezing Trap

**Comment by junsix** [comment]
이슈 재현 방법 : vs2017 테스트 -> 실행.

**Comment by yuneg11** [comment]
### 테스트 실행 방법
> 테스트 > 실행 > 모든 테스트
또는
> Ctrl+R, A

### 테스트 결과 확인
테스트 탐색기에서 통과하지 못한 항목들이 나타남
