### ISSUE TITLE
번역이 필요한 부분확인 

### ISSUE THREAD

**Issue by rjsgmlsms126** [18-2-SKKU-OSS/2018-2-OSS-L6#21]
### Actual Behavior
1.외래어 표기
2.잘못된 번역
3.잘못된 번역

### Steps to reproduce behavior
1.최근 다시보기
2.다시보기 통계
3.다시보기 파일

### Log/Screenshots
```
  <data name="MainWindow_Menu_Replays_Latest" xml:space="preserve">
    <value>최근 리플레이(_L)</value>
  </data>
  <data name="MainWindow_Menu_Replays_Stats" xml:space="preserve">
    <value>통계에서 선택(_S)</value>
  </data>
  <data name="MainWindow_Menu_Replays_File" xml:space="preserve">
    <value>파일로부터 로드(_F)</value>
  </data>


```

**Comment by yuneg11** [comment]
어느 화면에 나오는 문자열인가요?
문맥을 알 수 있으면 더 좋을 것 같아요.

**Comment by rjsgmlsms126** [comment]
<img width="960" alt="2018-12-06" src="https://user-images.githubusercontent.com/27187597/49525207-9b87ae00-f8f0-11e8-9132-a9e5bfdb0600.png">
이부분입니다.

**Comment by yuneg11** [comment]
해결된 것 확인했습니다.
