### ISSUE TITLE
프로젝트 코드 분석 @junsix @yuneg11

### ISSUE THREAD

**Issue by junsix** [18-2-SKKU-OSS/2018-2-OSS-L6#23]
![image](https://user-images.githubusercontent.com/29080894/49520794-69258300-f8e7-11e8-9c5a-a62501c1e157.png)

문제가 되는 테스트 코드.

**Comment by yuneg11** [comment]
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/74cdd087f32c0f193a0217ee99fb29cd449a85d0/HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs#L169-L187

해당 코드입니다

**Comment by yuneg11** [comment]
오류 메시지: 

> Message: Assert.AreEqual failed. Expected:<True>. Actual:<False>. Freezing Trap

위의 테스트 중에서도 174~175번째 줄과 182~183번째 줄에서 문제가 생기는 것 같습니다.
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/74cdd087f32c0f193a0217ee99fb29cd449a85d0/HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs#L174-L175
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/74cdd087f32c0f193a0217ee99fb29cd449a85d0/HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs#L182-L183

**Comment by junsix** [comment]
오후 10:40:58|Info|Player.Draw >> [Player] id=28, cardId=UNG_960, cardName=Lost in the Jungle, zonePos=10,Info={turn=6, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
오후 10:41:04|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
오후 10:41:07|Info|Player.SecretTriggered >> [Opponent] id=87, cardId=EX1_610, cardName=Explosive Trap, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=HAND, OriginalController=2}
오후 10:41:07|Info|SecretsEventHandler.HandleAttack >> attacker health : -1
오후 10:41:07|... 1 duplicate messages
오후 10:41:07|Info|SecretsManager.Exclude >> Excluded Secret EX1_130
오후 10:41:07|Info|SecretsManager.Exclude >> Excluded Secret EX1_289
오후 10:41:07|Info|SecretsManager.Exclude >> Excluded Secret LOOT_079
오후 10:41:07|Info|SecretsManager.Exclude >> Excluded Secret EX1_610
오후 10:41:07|Info|SecretsManager.Exclude >> Excluded Secret EX1_533
오후 10:41:07|Info|SecretsManager.Exclude >> Excluded Secret LOOT_210
오후 10:41:07|Info|SecretsManager.Exclude >> Excluded Secret EX1_594
오후 10:41:07|Info|SecretsManager.Exclude >> Excluded Secret EX1_610
오후 10:41:09|Info|Player.CreateInPlay >> [Opponent] id=100, cardId=LOOT_134, cardName=Toothy Chest, zonePos=2,Info={turn=6, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=2}
오후 10:41:14|Info|Player.SecretTriggered >> [Opponent] id=35, cardId=LOOT_079, cardName=Wandering Monster, zonePos=0,Info={turn=6, originalZone=DECK, hidden=true, OriginalController=2}
오후 10:41:14|Info|SecretsManager.Exclude >> Excluded Secret LOOT_079
0x7204 스레드가 종료되었습니다(코드: 0 (0x0)).
오후 10:41:16|Info|Player.PlayToGraveyard >> [Player] id=29, cardId=ICC_038, cardName=Righteous Protector, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=1}
오후 10:41:16|Info|Player.PlayToGraveyard >> [Player] id=82, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:16|Info|Player.PlayToGraveyard >> [Player] id=90, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:16|Info|Player.PlayToGraveyard >> [Player] id=91, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:16|Info|Player.PlayToGraveyard >> [Player] id=93, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:16|Info|Player.PlayToGraveyard >> [Player] id=94, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:17|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:AT_132_PALADIN turn:6 from:-1)
오후 10:41:17|Info|SecretsManager.Exclude >> Excluded Secret LOE_021
오후 10:41:18|Info|Player.CreateInPlay >> [Player] id=101, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=1,Info={turn=6, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=1}
오후 10:41:18|Info|Player.CreateInPlay >> [Player] id=102, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=2,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:19|Info|Player.Play >> [Player] id=32, cardId=LOOT_149, cardName=Corridor Creeper, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=1}
오후 10:41:19|Info|SecretsManager.Exclude >> Excluded Secret EX1_609
오후 10:41:19|Info|SecretsManager.Exclude >> Excluded Secret LOOT_101
오후 10:41:19|Info|SecretsManager.Exclude >> Excluded Secret CFM_620
오후 10:41:19|Info|SecretsManager.Exclude >> Excluded Secret EX1_379
오후 10:41:19|Info|SecretsManager.Exclude >> Excluded Secret EX1_294
오후 10:41:19|Info|SecretsManager.Exclude >> Excluded Secret ICC_082
오후 10:41:20|Info|Player.PlayToGraveyard >> [Player] id=84, cardId=LOOT_149e, cardName=Creepier, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:20|Info|Player.Play >> [Player] id=9, cardId=LOOT_149, cardName=Corridor Creeper, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=1}
오후 10:41:20|Info|SecretsManager.Exclude >> Excluded Secret LOE_027
오후 10:41:20|Info|SecretsManager.Exclude >> Excluded Secret EX1_609
오후 10:41:20|Info|SecretsManager.Exclude >> Excluded Secret LOOT_101
오후 10:41:20|Info|SecretsManager.Exclude >> Excluded Secret CFM_620
오후 10:41:20|Info|SecretsManager.Exclude >> Excluded Secret EX1_379
오후 10:41:20|Info|SecretsManager.Exclude >> Excluded Secret EX1_294
오후 10:41:20|Info|SecretsManager.Exclude >> Excluded Secret ICC_082
오후 10:41:20|Info|Player.PlayToGraveyard >> [Player] id=83, cardId=LOOT_149e, cardName=Creepier, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:21|Info|Player.Play >> [Player] id=28, cardId=UNG_960, cardName=Lost in the Jungle, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=1}
오후 10:41:21|Info|Player.CreateInPlay >> [Player] id=106, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=5,Info={turn=6, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=1}
오후 10:41:21|Info|Player.CreateInPlay >> [Player] id=107, cardId=CS2_101t, cardName=Silver Hand Recruit, zonePos=6,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
오후 10:41:21|Info|SecretsManager.Exclude >> Excluded Secret GIL_577
오후 10:41:21|Info|SecretsManager.Exclude >> Excluded Secret GIL_903
오후 10:41:21|Info|SecretsManager.Exclude >> Excluded Secret EX1_287
오후 10:41:21|Info|SecretsManager.Exclude >> Excluded Secret UNG_024
오후 10:41:21|Info|SecretsManager.Exclude >> Excluded Secret KAR_004
오후 10:41:22|Info|Player.PlayToGraveyard >> [Player] id=28, cardId=UNG_960, cardName=Lost in the Jungle, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=1}

에러 주석

**Comment by junsix** [comment]
그 부분 테스트 부분이라 주석으로 건너 뛰면 안되고 거기 앞에 체력 주면 고쳐져요.
