### ISSUE TITLE
Comment로 코드를 올리는 법

### ISSUE THREAD

**Issue by yuneg11** [18-2-SKKU-OSS/2018-2-OSS-L6#24]
출처: [Opening an issue from code](https://help.github.com/articles/opening-an-issue-from-code/)

Code 탭에서 해당 파일을 찾아서 열면 Line이나 Range를 설정하고 Copy permalink를 클릭하면 됩니다.
Line 설정은 해당 Line 번호를 누르면 되고 Range 설정은 시작 Line을 클릭한 뒤 종료 Line을 Shift키를 누른 후 클릭하면 됩니다.

**Comment by yuneg11** [comment]
### 1. Code 탭 클릭
<img width="583" alt="image" src="https://user-images.githubusercontent.com/2123763/49529574-aabf2980-f8f9-11e8-8a9c-21aeeedd7020.png">

### 2. 해당 파일 열기
<img width="777" alt="image" src="https://user-images.githubusercontent.com/2123763/49529637-cfb39c80-f8f9-11e8-9196-b1dc306e5c50.png">

### 3. 필요한 코드 선택
시작 Line 번호 클릭 후 종료 Line 번호를 Shift키를 누른 채로 클릭
<img width="688" alt="image" src="https://user-images.githubusercontent.com/2123763/49529719-04275880-f8fa-11e8-879e-06fc8e95a0dc.png">

### 4. Copy permalink 선택
<img width="323" alt="image" src="https://user-images.githubusercontent.com/2123763/49529816-3b960500-f8fa-11e8-92fb-75eb29e2fd38.png">

### 5. Markdown으로 작성
그대로 붙여넣으면 링크가 생김
<img width="405" alt="image" src="https://user-images.githubusercontent.com/2123763/49529896-62ecd200-f8fa-11e8-8764-b08ffdc958fa.png">


### 결과
<img width="658" alt="image" src="https://user-images.githubusercontent.com/2123763/49529980-8f085300-f8fa-11e8-8d76-c5bd7097fca2.png">

**Comment by junsix** [comment]
이 내용을 위키에도 올려주면 좋을거 같아요

**Comment by yuneg11** [comment]
[위키](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki/Comment로-코드를-올리는-법)에도 추가했습니다.
