### ISSUE TITLE
유닛테스트 추가 @junsix

### ISSUE THREAD

**Issue by junsix** [18-2-SKKU-OSS/2018-2-OSS-L6#25]
폭발의 덫에 의해 하수인이 죽을때 빙결의 덫이 덫 리스트에서 지워지지 않는 테스트 추가.

함수 네이밍 추천 부탁드립니다.

**Comment by yuneg11** [comment]
SingleSecret_ExplosiveTrapToMinion_FreezingTrapRemoveTest() 같은건 어떤가요?
네이밍 해놓은걸 보니까 SingleSecret 또는 MultipleSecret이 먼저 나오고 행위자와 대상이 나온 뒤에 결과나 행동이 마지막으로 나오는 것 같아요.

**Comment by junsix** [comment]
저는 비밀이 2개 걸린 상태라 MultipleSecrets
미니언이 영웅을 공격하는 상태라 MinionToHero
폭발의 덫이 미니언을 죽이니까 ExplosiveTrapTriggered_MinionDied
플레이어를 공격할때 발동하니가 PlayerAttackTest 라해서 
MultipleSecrets_MinionToHero_ExplosiveTrapTriggered_MinionDied_PlayerAttackTest라 생각해 봤는데 어떻게 생각하세요?

**Comment by yuneg11** [comment]
이름이 길어지긴 하네요...
그래도 의미를 생각해보면 괜찮은것 같은데요?

**Comment by junsix** [comment]
음 의미가 중복 되는게 있네요

**Comment by junsix** [comment]
MultipleSecrets_MinionToHero_ExplosiveTrapTriggered_MinionDied_PlayerAttackTest 로 우선 커밋을 해 두었습니다.
