### ISSUE TITLE
유닛 테스트 이슈를 위한 브랜치 생성 @yuneg11

### ISSUE THREAD

**Issue by yuneg11** [18-2-SKKU-OSS/2018-2-OSS-L6#27]
유닛 테스트 이슈를 다루기 위한 브랜치를 생성했습니다.
앞으로 관련 커밋은 [unit_test](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/tree/unit_test) 브랜치에 해주세요.

**Comment by junsix** [comment]
git branch -r 해서 볼 때 unit_test브랜치가 안나오던데 확인 부탁드려요.

**Comment by junsix** [comment]
아 실수로 git pull을 안했었네요.

**Comment by yuneg11** [comment]
https://cjh5414.github.io/get-git-remote-branch/
이 글에 잘 나와 있어서 혹시 잘 모르시는 분들은 한번 봐주세요

**Comment by junsix** [comment]
localization 을 위한 브랜치도 생성했습니다.\

각각 브랜치 관련해서 작업해야 될 내용을 위키에 정리 부탁드려도 될까요?

**Comment by yuneg11** [comment]
네 알겠습니다
