### ISSUE TITLE
공식 한국어 번역 자료가 있나요

### ISSUE THREAD

**Issue by yuneg11** [18-2-SKKU-OSS/2018-2-OSS-L6#28]
공식 번역이 정리된 사이트가 있으면 웹 크롤링으로 데이터를 가져올 수 있을 것 같은데 혹시 관련 사이트가 있나요?

**Comment by junsix** [comment]
https://playhearthstone.com/ko-kr/expansions-adventures/rastakhans-rumble/cards

**Comment by junsix** [comment]
카드 관련 데이터는 여기서 볼수 있어요
 이미지라서 ocr도 같이 돌려야 될거 같아요.

**Comment by yuneg11** [comment]
텍스트로 된 자료가 아니면 좀 힘들겠네요
공식 사이트의 자료를 따로 텍스트 형식으로 보여주는 사이트가 있는지 찾아봐야겠어요

**Comment by yuneg11** [comment]
아무래도 크롤러 만들어서 데이터 모으고 정리하기엔 시간이 좀 부족할 것 같네요
