### ISSUE TITLE
코드 리뷰 0682101

### ISSUE THREAD

**Issue by yuneg11** [18-2-SKKU-OSS/2018-2-OSS-L6#35]
0682101ded572119b5c2bce64e90626104acc3ba 커밋에 대한 코드 리뷰

https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/0682101ded572119b5c2bce64e90626104acc3ba/HDTTests/Hearthstone/Secrets/SecretEventHandlerTest.cs#L169-L187

- [ ] 커밋 컨벤션: unit_test 브랜치에서 master 브랜치로 merge하는 과정에서 중복된 커밋이 생긴 것 같습니다.

**Comment by junsix** [comment]
#36 이슈랑 관련된 이슌가요?

**Comment by yuneg11** [comment]
네 나중에 알고보니까 제가 merge할 때 커밋 이름을 똑같이 해서 그렇더라고요
