### ISSUE TITLE
브랜치 merge시 주의할 점

### ISSUE THREAD

**Issue by yuneg11** [18-2-SKKU-OSS/2018-2-OSS-L6#36]
브랜치를 merge할 때 동일한 커밋이 여러개 생기는 문제가 발생하고 있습니다.
merge를 하기 전에 rebase나 pull을 통해 master브랜치에 있는 기록을 먼저 해당 브랜치에 업데이트한 후에 머지해 주세요

**Comment by junsix** [comment]
저희 정책을 merge보다 rebase를 우선으로 하는걸로 할껀가요?

**Comment by yuneg11** [comment]
제가 아까 커밋 기록을 잘 못 본 것 같아요
그냥 하던대로 merge하면 될 것 같아요
