### ISSUE TITLE
번역이 안 된 부분 번역 4

### ISSUE THREAD

**Issue by JunhyeonMoon** [18-2-SKKU-OSS/2018-2-OSS-L6#38]
- Line 2707 ~ 2719  
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/37b5cfcc8a03613d7cf42e5daec141cb04984dd8/HDT-Localization/Strings.ko-KR.resx#L2707-L2719

**Comment by rjsgmlsms126** [comment]
여기 스크린샷좀 부탁드릴게요

**Comment by yuneg11** [comment]
![image](https://user-images.githubusercontent.com/2123763/49728572-7d39fd80-fcb6-11e8-8f8b-bb8c2191ab4a.png)
맨 밑 부분인 것 같아요

**Comment by yuneg11** [comment]
해당 부분 번역 완료했습니다
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/ec0f334b24210be0008e76a315c5e2c25dcdd618/HDT-Localization/Strings.ko-KR.resx#L2706-L2720

검토해 주세요

**Comment by JunhyeonMoon** [comment]
Save only를 '저장만' 도 괜찮은데 다른 표현 없을까요?

**Comment by yuneg11** [comment]
문맥을 보니까 약간 의역해서 저장이나 저장하기로 바꿔도 되지 않을까요?

**Comment by kevhahn97** [comment]
간단하게 '저장'이 괜찮은 것 같습니다.
