### ISSUE TITLE
번역이 안 된 부분 번역 5

### ISSUE THREAD

**Issue by JunhyeonMoon** [18-2-SKKU-OSS/2018-2-OSS-L6#39]
- Line 2802 ~ 2804  
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/37b5cfcc8a03613d7cf42e5daec141cb04984dd8/HDT-Localization/Strings.ko-KR.resx#L2802-L2804

**Comment by kevhahn97** [comment]
> 날짜 형식에 대한 더 많은 정보에 대해서는 Google 검색창에 "C# date format"을 검색하세요.

"C# date format"이 좋을까요 "C# 날짜 형식"이 좋을까요?

**Comment by JunhyeonMoon** [comment]
저는 "C# 날짜 형식" 이 좋아보여요

**Comment by yuneg11** [comment]
저도 번역을 해 놓는게 좋아보여요

**Comment by kevhahn97** [comment]
여러분의 의견 수용하여 localization branch에 commit했습니다.
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/bcfd47a8a0e94ab727785e9588782b8e6585ba21/HDT-Localization/Strings.ko-KR.resx#L2802-L2804

**Comment by yuneg11** [comment]
확인했습니다
