### ISSUE TITLE
Commit 메세지 관련

### ISSUE THREAD

**Issue by kevhahn97** [18-2-SKKU-OSS/2018-2-OSS-L6#40]
master branch에서
"Update Strings.ko-KR.resx"
라는 커밋 메세지로 커밋된 게 3개정도 있는데, 커밋 메세지에 어떤 업데이트가 있었는지 추가 정보가 있어야 할 것 같은데 어떻게 생각하시나요?

**Comment by junsix** [comment]
![image](https://user-images.githubusercontent.com/29080894/49699344-39da8300-fc13-11e8-8493-569aa7e4c7fe.png)
 이런식으로 커밋하는게 좋을거 같아요.
