### ISSUE TITLE
위키에 프로젝트 빌드하는법 추가했습니다.

### ISSUE THREAD

**Issue by JunhyeonMoon** [18-2-SKKU-OSS/2018-2-OSS-L6#41]
제곧내
확인 부탁드려요

* [프로젝트를 빌드하는 방법](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/wiki/프로젝트-빌드하는-방법)

**Comment by junsix** [comment]
확인했습니다. 저기서 더 자세한 내용을 보려면 https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md 을 참조하면 좋을거 같습니다.

**Comment by junsix** [comment]
확인했습니다. 저기서 더 자세한 내용을 보려면 https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md 을 참조하면 좋을거 같습니다.

**Comment by JunhyeonMoon** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md 링크를 위키에 추가해놓을께요
