### ISSUE TITLE
CONTRIBUTING_KR.md 관련

### ISSUE THREAD

**Issue by kevhahn97** [18-2-SKKU-OSS/2018-2-OSS-L6#44]
CONTRIBUTIN_KR.md 파일을 localization branch에 추가했습니다.
[파일 링크](https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/localization/CONTRIBUTING_KR.md)를 확인하시고 의견 주시면 감사하겠습니다.

**Comment by JunhyeonMoon** [comment]
좋은거 같아요

**Comment by yuneg11** [comment]
네 좋아보여요

**Comment by rjsgmlsms126** [comment]
확인!

**Comment by kevhahn97** [comment]
master에 merge했습니다.
