### ISSUE TITLE
외래어 표기 문제를 해결한다.

### ISSUE THREAD

**Issue by junsix** [18-2-SKKU-OSS/2018-2-OSS-L6#5]
## Bug report
관용적으로 한국 사람들이 사용하는 표기와 프로그램이 보여주는 표기가 다름.

### Expected Behavior

트래커
### Actual Behavior

트랙커
### Log/Screenshots

![default](https://user-images.githubusercontent.com/29080894/49216924-9ff32900-f40f-11e8-9135-14f787d73742.PNG)

**Comment by junsix** [comment]
번역 관련 repository.
HDT-Localization repository.

**Comment by rjsgmlsms126** [comment]
네이버에서 확인했을때 국어사전에는 트레커가 올바른 표기가 맞네요
![cap 2018-12-04 18-45-11-442](https://user-images.githubusercontent.com/27187597/49433204-c5f44100-f7f4-11e8-966f-4b84f21fa6f4.png)

**Comment by rjsgmlsms126** [comment]
네이버 자동완성에서도 트랙커가 아니라 트래커가 맞네
![cap 2018-12-04 18-47-05-161](https://user-images.githubusercontent.com/27187597/49433319-14094480-f7f5-11e8-8d56-649f3c4eb80f.png)
요

**Comment by junsix** [comment]
localization 브랜치에 커밋했습니다.
