### ISSUE TITLE
번역이 안 된 부분 번역5

### ISSUE THREAD

**Issue by rjsgmlsms126** [18-2-SKKU-OSS/2018-2-OSS-L6#56]
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L6/blob/2f309b1f30a60d9990a96a2e58dbda609ddfe03b/HDT-Localization/Strings.ko-KR.resx#L2295-L2300

**Comment by rjsgmlsms126** [comment]
마지막으로 수정한 시간
마지막으로 실행한 시간
으로 번역 어떤가요?

**Comment by junsix** [comment]
2번째꺼 최근 실행 시간 어때요?

**Comment by rjsgmlsms126** [comment]
둘다 그럼 최근 수정 시간 최근 실행 시간으로 할게요
