### ISSUE TITLE
번역 되지 않은 문구를 번역한다.

### ISSUE THREAD

**Issue by junsix** [18-2-SKKU-OSS/2018-2-OSS-L6#6]
### Expected Behavior

토깽이 콩콩 스택 보기:
### Actual Behavior

Show Pogo-Hopper counter:
### Log/Screenshots

![image](https://user-images.githubusercontent.com/29080894/49218500-e5b1f080-f413-11e8-9ead-4fde9f0a2716.png)

![image](https://user-images.githubusercontent.com/29080894/49218406-ae434400-f413-11e8-80be-39f34f1f5dd8.png)

**Comment by JunhyeonMoon** [comment]
최근 프로젝트를 확인해 보니까 번역안된 문구가 수정돼 있네요.  
그런데 콩콩 카운터로 번역이 되있는데 위에는 스택이라고 하셨는데 그 이유는 뭔가요?  
만약 스택이라는 표현이 더 적합하면 수정하는게 맞는 거 같습니다  

![image](https://user-images.githubusercontent.com/37601694/49432980-3fd7fa80-f7f4-11e8-8456-343fe4682ae0.png)

**Comment by junsix** [comment]
토깽이 콩콩이 카드도 비취 골램과 유사하게 토깽이 콩콩이가 필드에 소환 될 때 마다 체력과 공격력이 올라가게 되어있습니다. 따라서 카운터라는 단어보다 스택이라는 단어가 더 올바른 표현이라고 생각합니다.
