### ISSUE TITLE
향상된 엘레크 + 팔도레이 순찰자냈을 때 3장의 잠복만이 덱트레커이 기록됨.

### ISSUE THREAD

**Issue by junsix** [18-2-SKKU-OSS/2018-2-OSS-L6#7]
## Bug report
향상된 엘레크 + 팔도레이 순찰자냈을 때 3장의 잠복만이 덱트레커이 기록됨.
### Expected Behavior

6장의 잠복이 기록됨.
### Actual Behavior

3자의 잠복이 기록됨.
### Log/Screenshots

![default](https://user-images.githubusercontent.com/29080894/49222903-91613d80-f420-11e8-87ab-0153aa704127.PNG)

**Comment by yuneg11** [comment]
이 문제는 해결 된건가요?

**Comment by junsix** [comment]
이 부분 소스 분석 중이에요.

**Comment by junsix** [comment]
이슈 해결.
